# Generated by Django 6.0.7 on 2026-07-10 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('tarjeta', 'Tarjeta Visa/MasterCard'), ('yape', 'Yape'), ('plin', 'Plin'), ('transferencia', 'Transferencia bancaria'), ('contra_entrega', 'Pago contra entrega')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia_transaccion', models.CharField(blank=True, max_length=100)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='ventas.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('boleta', 'Boleta'), ('factura', 'Factura')], max_length=10)),
                ('serie', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igv', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='pagos.pago')),
            ],
            options={
                'unique_together': {('serie', 'numero')},
            },
        ),
    ]
