# Generated by Django 6.0.7 on 2026-07-10 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
        ('usuarios', '0002_perfilcliente_perfilempleado_perfilrepartidor'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('asignada', 'Asignada'), ('preparado', 'Preparado'), ('en_camino', 'En camino'), ('entregado', 'Entregado'), ('fallida', 'Entrega fallida')], default='asignada', max_length=20)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('motivo_fallo', models.CharField(blank=True, choices=[('cliente_ausente', 'Cliente ausente'), ('direccion_incorrecta', 'Dirección incorrecta'), ('otro', 'Otro motivo')], max_length=30)),
                ('fecha_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='entrega', to='ventas.pedido')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas', to='usuarios.perfilrepartidor')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='logistica.zona')),
            ],
        ),
    ]
